begin;

delete from public.case_events;
delete from public.cases;

insert into public.cases (
  id, patient_name, patient_id, request_id, medication_or_procedure, payer,
  provider_name, provider_reference, diagnosis_context,
  submitted_date, status, priority, notes, clinical_facts, policy_facts
) values
('10000000-0000-4000-8000-000000000001', 'Avery Morgan', 'PT-1001', 'PA-24001', 'Dupixent 300 mg', 'Northwind Health', 'Harbor Dermatology Demo Clinic', 'PRV-2001', 'Fictional diagnosis L20.9; severe atopic dermatitis.', '2026-09-12', 'new', 'high', 'Severe atopic dermatitis; complete fictional chart attached.', 'Diagnosis L20.9. Symptoms affect 22% body surface area. Failed 12-week demo trials of topical corticosteroid and tacrolimus. Prescriber attestation and current labs are attached.', 'Demo medication policy requires documented diagnosis, over 10% body surface area, two failed topical therapies, and prescriber attestation.'),
('10000000-0000-4000-8000-000000000002', 'Jordan Lee', 'PT-1002', 'PA-24002', 'Humira 40 mg', 'Contoso Care', 'Summit Rheumatology Demo Group', 'PRV-2002', 'Fictional rheumatoid arthritis treatment review.', '2026-09-13', 'new', 'normal', 'Fictional clinical note attached; baseline screening absent.', 'Demo diagnosis: rheumatoid arthritis. Methotrexate trial documented. No tuberculosis screening result or hepatitis B panel is present.', 'Demo policy requires a negative TB screen and hepatitis B panel within 12 months.'),
('10000000-0000-4000-8000-000000000003', 'Riley Chen', 'PT-1003', 'PA-24003', 'Cosmetic rhinoplasty', 'Northwind Health', 'Lakeside Plastic Surgery Demo Center', 'PRV-2003', 'Fictional cosmetic procedure request without functional diagnosis.', '2026-09-11', 'new', 'normal', 'Requested solely for fictional cosmetic preference.', 'The demo surgeon documents no functional impairment, trauma, congenital defect, or breathing obstruction. Request reason is cosmetic appearance only.', 'Demo plan benefit excludes procedures performed solely for cosmetic appearance without functional impairment.'),
('10000000-0000-4000-8000-000000000004', 'Morgan Patel', 'PT-1004', 'PA-24004', 'Lumbar MRI', 'Fabrikam Benefits', 'Pine Valley Neurology Demo Practice', 'PRV-2004', 'Fictional lumbar symptoms with newly documented left foot weakness.', '2026-09-14', 'new', 'high', 'New fictional weakness noted; specialist review requested.', 'Six weeks of demo conservative therapy completed. Latest fictional exam documents new left foot weakness. No emergent red-flag diagnosis is confirmed.', 'Demo imaging policy sends new neurologic deficits to clinical review before a coverage decision.'),
('10000000-0000-4000-8000-000000000005', 'Casey Williams', 'PT-1005', 'PA-24005', 'Knee arthroplasty', 'Contoso Care', 'Metro Orthopedic Demo Institute', 'PRV-2005', 'Fictional advanced knee osteoarthritis procedure history.', '2026-09-08', 'closed', 'normal', 'Approved, performed, and administratively closed in this fictional workflow.', 'Demo procedure completed after authorization. No remaining tasks.', 'Completed demo requests should remain closed unless a correction is received.'),
('10000000-0000-4000-8000-000000000006', 'Taylor Brooks', 'PT-1006', 'PA-24006', 'Ozempic 1 mg', 'Fabrikam Benefits', 'Cedar Endocrinology Demo Clinic', 'PRV-2006', 'Fictional conflicting type 2 diabetes and weight-management documentation.', '2026-09-15', 'new', 'normal', 'Fictional chart contains conflicting diagnosis codes.', 'Demo problem list includes E11.9 type 2 diabetes, while the visit note says weight management and no diabetes history. Fictional A1C is 6.0%.', 'Demo coverage requires confirmed type 2 diabetes. Conflicting clinical documentation must be resolved before a final decision.'),
('10000000-0000-4000-8000-000000000007', 'Drew Kim', 'PT-1007', 'PA-24007', 'Physical therapy, 12 visits', 'Northwind Health', 'Northstar Rehabilitation Demo Center', 'PRV-2007', 'Fictional rehabilitation plan following musculoskeletal injury.', '2026-09-10', 'approved', 'low', 'Approved for 12 fictional visits through 2026-12-31.', 'Demo authorization was approved after plan review. Approval notification sent.', 'No further action is needed unless the fictional provider requests additional visits.'),
('10000000-0000-4000-8000-000000000008', 'Skyler Davis', 'PT-1008', 'PA-24008', 'Sleep study', 'Contoso Care', 'Moonlight Sleep Demo Clinic', 'PRV-2008', 'Fictional fatigue and snoring evaluation for sleep-study review.', '2026-09-16', 'needs_information', 'normal', 'Requested prior fictional sleep notes from ordering clinic.', 'Demo order includes fatigue and snoring. Epworth score and prior home-study result have not been received.', 'Demo policy requires an Epworth score and documentation of any prior home sleep study.');

insert into public.case_events(case_id, previous_status, new_status, action, note, actor)
select id, status, status, 'seeded', 'Initial fictional demo record.', 'system'
from public.cases;

commit;
