begin;

delete from public.case_events;
delete from public.cases;

insert into public.cases (
  id, patient_name, patient_id, request_id, medication_or_procedure, payer,
  provider_name, provider_reference, diagnosis_context,
  submitted_date, status, priority, notes, clinical_facts, policy_facts
) values
('10000000-0000-4000-8000-000000000001', 'Avery Morgan', 'PT-1001', 'PA-24001', 'Dupixent 300 mg', 'Northwind Health', 'Harbor Dermatology Demo Clinic', 'PRV-2001', 'Fictional criteria-complete therapy request.', '2026-09-12', 'new', 'high', 'All fictional chart sections and payer fields are complete.', 'Prior therapies attempted: 2. Supporting documentation: complete and attached. All required criteria are satisfied. Prescriber attestation and current labs are attached.', 'Minimum prior therapies: 2. Supporting documentation, prescriber attestation, and current labs are required.'),
('10000000-0000-4000-8000-000000000002', 'Jordan Lee', 'PT-1002', 'PA-24002', 'Humira 40 mg', 'Contoso Care', 'Summit Rheumatology Demo Group', 'PRV-2002', 'Fictional request with an explicitly absent required document.', '2026-09-13', 'new', 'normal', 'Supporting documentation: missing.', 'Supporting documentation: missing. The required tuberculosis screening result is not present. The hepatitis B panel has not been received.', 'The demo contract requires both screening documents and maps absent required documents to request information, not denial.'),
('10000000-0000-4000-8000-000000000003', 'Riley Chen', 'PT-1003', 'PA-24003', 'Cosmetic rhinoplasty', 'Northwind Health', 'Lakeside Plastic Surgery Demo Center', 'PRV-2003', 'Fictional request that explicitly fails a required benefit criterion.', '2026-09-11', 'new', 'normal', 'The complete fictional record establishes the stated exclusion.', 'Criteria not met. The request is solely for cosmetic appearance with no functional impairment. The complete record confirms no covered reconstructive indication.', 'The demo benefit excludes procedures solely for cosmetic appearance with no functional impairment; this explicit criterion failure maps to denial.'),
('10000000-0000-4000-8000-000000000004', 'Morgan Patel', 'PT-1004', 'PA-24004', 'Lumbar MRI', 'Fabrikam Benefits', 'Pine Valley Neurology Demo Practice', 'PRV-2004', 'Fictional request explicitly requiring specialist review.', '2026-09-14', 'new', 'high', 'Specialist review is explicitly required before a coverage decision.', 'Six weeks of conservative therapy are documented. A new fictional neurologic deficit requires specialist review before a coverage decision.', 'The demo contract explicitly maps this neurologic-deficit scenario to specialist review and pending review, not approval or denial.'),
('10000000-0000-4000-8000-000000000005', 'Casey Williams', 'PT-1005', 'PA-24005', 'Knee arthroplasty', 'Contoso Care', 'Metro Orthopedic Demo Institute', 'PRV-2005', 'Fictional completed procedure history.', '2026-09-08', 'closed', 'normal', 'Approved, performed, and administratively closed in this fictional workflow.', 'The demo procedure is complete and the case is closed.', 'Completed demo requests remain closed unless a later revision introduces new work.'),
('10000000-0000-4000-8000-000000000006', 'Taylor Brooks', 'PT-1006', 'PA-24006', 'Ozempic 1 mg', 'Fabrikam Benefits', 'Cedar Endocrinology Demo Clinic', 'PRV-2006', 'Fictional explicitly conflicting documentation.', '2026-09-15', 'new', 'normal', 'Conflicting facts must be resolved before any mutation.', 'Conflicting facts: one record states confirmed type 2 diabetes while another states there is no diabetes history.', 'The demo contract prohibits approval or denial while these inconsistent facts remain unresolved.'),
('10000000-0000-4000-8000-000000000007', 'Drew Kim', 'PT-1007', 'PA-24007', 'Physical therapy, 12 visits', 'Northwind Health', 'Northstar Rehabilitation Demo Center', 'PRV-2007', 'Fictional completed authorization.', '2026-09-10', 'approved', 'low', 'Approved for 12 fictional visits through 2026-12-31.', 'The demo authorization is already approved and unchanged.', 'No further action is needed unless the fictional provider submits changed evidence.'),
('10000000-0000-4000-8000-000000000008', 'Skyler Davis', 'PT-1008', 'PA-24008', 'Sleep study', 'Contoso Care', 'Moonlight Sleep Demo Clinic', 'PRV-2008', 'Fictional request awaiting information.', '2026-09-16', 'needs_information', 'normal', 'The case is already awaiting specifically requested information.', 'The requested Epworth score and prior home-study result have not been received.', 'The demo contract requires those documents before the case becomes actionable again.'),
('10000000-0000-4000-8000-000000000009', 'Alex Rivera', 'PT-1009', 'PA-24009', 'Observation-only review', 'Fabrikam Benefits', 'Harbor Demo Clinic', 'PRV-2009', 'Fictional case with no authorized state change.', '2026-09-17', 'new', 'low', 'No mutation is appropriate; observe without changing.', 'No mutation is appropriate. No authorized action is available from the current observed facts.', 'The demo contract requires a later external revision before any state-changing action is authorized.'),
('10000000-0000-4000-8000-000000000010', 'Quinn Harper', 'PT-1010', 'PA-24010', 'Biologic therapy renewal', 'Northwind Health', 'Oak Ridge Demo Clinic', 'PRV-2010', 'Fictional second criteria-complete request.', '2026-09-18', 'new', 'high', 'The complete record explicitly satisfies every configured criterion.', 'Prior therapies attempted: 4. Supporting documentation is complete and attached. Current labs and prescriber attestation are attached.', 'Minimum prior therapies: 3. The attached documentation, labs, and attestation satisfy all required criteria.'),
('10000000-0000-4000-8000-000000000011', 'Emerson Lane', 'PT-1011', 'PA-24011', 'Excluded cosmetic service', 'Contoso Care', 'Maple Demo Surgery Center', 'PRV-2011', 'Fictional second explicit exclusion.', '2026-09-18', 'new', 'normal', 'The complete record explicitly establishes the exclusion.', 'Criteria not met. The complete record confirms the service is solely cosmetic and has no functional indication.', 'The configured demo criterion explicitly excludes a solely cosmetic service with no functional indication and maps it to denial.'),
('10000000-0000-4000-8000-000000000012', 'Sage Bennett', 'PT-1012', 'PA-24012', 'Advanced imaging authorization', 'Fabrikam Benefits', 'Willow Neurology Demo Practice', 'PRV-2012', 'Fictional third criteria-complete request.', '2026-09-18', 'new', 'normal', 'All required evidence is documented and attached.', 'Prior therapies attempted: 5. Supporting documentation is complete and attached. The required clinical criteria are satisfied.', 'Minimum prior therapies: 2. Complete supporting documentation is required and is present.'),
('10000000-0000-4000-8000-000000000013', 'Rowan Ellis', 'PT-1013', 'PA-24013', 'Noncovered experimental service', 'Northwind Health', 'Canyon Demo Medical Group', 'PRV-2013', 'Fictional third explicit criterion failure.', '2026-09-18', 'new', 'high', 'The complete record establishes the configured criterion failure.', 'Prior therapies attempted: 0. The complete record directly proves the required prior-therapy criterion fails.', 'Minimum prior therapies: 2. The configured demo contract maps this complete-record criterion failure to denial.'),
('10000000-0000-4000-8000-000000000014', 'Parker Monroe', 'PT-1014', 'PA-24014', 'Infusion authorization', 'Contoso Care', 'River Demo Infusion Center', 'PRV-2014', 'Fictional request with an explicit required field absent.', '2026-09-18', 'new', 'normal', 'A payer-required field is missing.', 'The payer-required treatment frequency field is empty. All submitted clinical documents are otherwise present.', 'The demo contract maps an explicitly missing payer-required field to request information.'),
('10000000-0000-4000-8000-000000000015', 'Finley Scott', 'PT-1015', 'PA-24015', 'Therapy extension', 'Fabrikam Benefits', 'Pioneer Demo Therapy Group', 'PRV-2015', 'Fictional request awaiting a provider answer.', '2026-09-18', 'new', 'normal', 'The required provider response has not been received.', 'Provider response not received for the explicitly requested current functional assessment.', 'The demo contract maps an absent required provider response to request information.'),
('10000000-0000-4000-8000-000000000016', 'Dakota Reed', 'PT-1016', 'PA-24016', 'Authorization packet submission', 'Northwind Health', 'Beacon Demo Clinic', 'PRV-2016', 'Fictional packet ready for payer submission.', '2026-09-18', 'new', 'normal', 'The packet is ready for submission.', 'Authorization packet is signed and complete. Destination payer is selected.', 'The demo contract maps a signed complete packet with selected destination payer to submission.'),
('10000000-0000-4000-8000-000000000017', 'Reese Jordan', 'PT-1017', 'PA-24017', 'Specialist exception review', 'Contoso Care', 'Summit Demo Specialty Center', 'PRV-2017', 'Fictional explicit manual-review route.', '2026-09-18', 'new', 'high', 'Specialist review is explicitly required.', 'The configured exception requires specialist review before any final coverage decision.', 'The demo contract maps this explicit review requirement to pending review.'),
('10000000-0000-4000-8000-000000000018', 'Cameron Blake', 'PT-1018', 'PA-24018', 'Completed submission follow-up', 'Fabrikam Benefits', 'Harbor Demo Clinic', 'PRV-2018', 'Fictional pending item with finished work.', '2026-09-18', 'pending_review', 'low', 'No outstanding work remains.', 'Payer receipt confirmed. No outstanding work remains.', 'The demo contract maps confirmed payer receipt with no outstanding work to close.');

insert into public.case_events(case_id, previous_status, new_status, action, note, actor)
select id, status, status, 'seeded', 'Initial fictional demo record.', 'system'
from public.cases;

commit;
