// Deterministic synthetic file contents for the MedPoint LOCAL MOCK / DEMO dataset.
// Nothing here is derived from real documents.

const BANNER = 'LOCAL MOCK / DEMO - NO REAL DATA'

function pdfEscape(text) {
  return String(text).replace(/[\\()]/g, (c) => `\\${c}`).replace(/[^\x20-\x7e]/g, '-')
}

/** Builds a minimal, valid single-page PDF containing the given text lines. */
export function makePdf(lines) {
  const content = [
    'BT',
    '/F1 12 Tf',
    '14 TL',
    '72 740 Td',
    ...[BANNER, '', ...lines].map((line) => `(${pdfEscape(line)}) '`),
    'ET',
  ].join('\n')
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  let body = '%PDF-1.4\n'
  const offsets = []
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(body))
    body += `${index + 1} 0 obj\n${object}\nendobj\n`
  })
  const xrefOffset = Buffer.byteLength(body)
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  body += offsets.map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return Buffer.from(body, 'latin1')
}

export function makeText(lines) {
  return Buffer.from([BANNER, '', ...lines, ''].join('\n'), 'utf8')
}

export function syntheticFile({ mimeType, title, lines }) {
  const all = [title, ...lines, 'Generated by the demo seed process. Contains no patient information.']
  return mimeType === 'application/pdf' ? makePdf(all) : makeText(all)
}
