create extension if not exists pgcrypto;

create table if not exists public.cases (
  id uuid primary key default gen_random_uuid(),
  patient_name text not null,
  patient_id text not null,
  request_id text not null unique,
  medication_or_procedure text not null,
  payer text not null,
  submitted_date date not null,
  status text not null check (status in ('new', 'pending_review', 'needs_information', 'approved', 'denied', 'submitted', 'closed')),
  priority text not null check (priority in ('high', 'normal', 'low')),
  notes text not null default '',
  clinical_facts text not null,
  policy_facts text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.case_events (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.cases(id) on delete cascade,
  created_at timestamptz not null default now(),
  previous_status text not null,
  new_status text not null,
  action text not null,
  note text not null default '',
  actor text not null check (actor in ('demo_user', 'browser_agent', 'simulator', 'system'))
);

create index if not exists cases_status_updated_idx on public.cases(status, updated_at desc);
create index if not exists case_events_case_created_idx on public.case_events(case_id, created_at desc);

alter table public.cases enable row level security;
alter table public.case_events enable row level security;

revoke all on public.cases from anon;
revoke all on public.case_events from anon;
revoke all on public.cases from authenticated;
revoke all on public.case_events from authenticated;
grant select on public.cases to authenticated;
grant select on public.case_events to authenticated;

create policy "authenticated users can read cases"
on public.cases for select
to authenticated
using (auth.uid() is not null);

create policy "authenticated users can read case events"
on public.case_events for select
to authenticated
using (auth.uid() is not null);

create or replace function public.perform_case_action(
  p_case_id uuid,
  p_action text,
  p_note text default ''
)
returns public.cases
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_previous_status text;
  v_new_status text;
  v_case public.cases;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  v_new_status := case p_action
    when 'approve' then 'approved'
    when 'deny' then 'denied'
    when 'request_information' then 'needs_information'
    when 'submit' then 'submitted'
    when 'move_pending' then 'pending_review'
    when 'close' then 'closed'
    else null
  end;

  if v_new_status is null then
    raise exception 'Unsupported action';
  end if;
  if p_action in ('deny', 'request_information') and btrim(coalesce(p_note, '')) = '' then
    raise exception 'A reason is required for this action';
  end if;

  select status into v_previous_status from public.cases where id = p_case_id for update;
  if not found then
    raise exception 'Case not found';
  end if;

  update public.cases
  set status = v_new_status, updated_at = now()
  where id = p_case_id
  returning * into v_case;

  insert into public.case_events(case_id, previous_status, new_status, action, note, actor)
  values (p_case_id, v_previous_status, v_new_status, p_action, btrim(coalesce(p_note, '')), 'demo_user');

  return v_case;
end;
$$;

create or replace function public.simulate_case_change()
returns public.cases
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_case public.cases;
  v_suffix text := substr(replace(gen_random_uuid()::text, '-', ''), 1, 10);
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select * into v_case
  from public.cases
  where status in ('pending_review', 'needs_information')
    and notes not like '%Simulator update: requested information received.%'
  order by updated_at
  limit 1
  for update;

  if found then
    update public.cases
    set notes = notes || E'\nSimulator update: requested information received.', updated_at = now()
    where id = v_case.id
    returning * into v_case;

    insert into public.case_events(case_id, previous_status, new_status, action, note, actor)
    values (v_case.id, v_case.status, v_case.status, 'information_received', 'Requested fictional documentation arrived.', 'simulator');
  else
    insert into public.cases(
      patient_name, patient_id, request_id, medication_or_procedure, payer,
      submitted_date, status, priority, notes, clinical_facts, policy_facts
    ) values (
      'Simulation Patient ' || upper(substr(v_suffix, 1, 4)),
      'SIM-PT-' || upper(substr(v_suffix, 1, 6)),
      'SIM-PA-' || upper(v_suffix),
      'Fictional specialty medication review',
      'Demo Health Plan', current_date, 'new', 'normal',
      'New fictional request entered the demo queue.',
      'Demo clinical packet includes a diagnosis and treatment history but requires agent review.',
      'Demo policy facts are available; the application does not recommend a decision.'
    ) returning * into v_case;

    insert into public.case_events(case_id, previous_status, new_status, action, note, actor)
    values (v_case.id, 'new', 'new', 'simulator_created', 'New fictional case entered the queue.', 'simulator');
  end if;

  return v_case;
end;
$$;

revoke all on function public.perform_case_action(uuid, text, text) from public, anon;
revoke all on function public.simulate_case_change() from public, anon;
grant execute on function public.perform_case_action(uuid, text, text) to authenticated;
grant execute on function public.simulate_case_change() to authenticated;

-- Supabase projects have this publication. The guard keeps local Postgres migration tests portable.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'cases') then
      alter publication supabase_realtime add table public.cases;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'case_events') then
      alter publication supabase_realtime add table public.case_events;
    end if;
  end if;
end
$$;
